version: "3.4"

services: 
  api:
    build:
      context: .
    image: 'gobarber-api:latest'
    command: yarn dev:server
    ports: 
      - "3333:3333"
    volumes: 
      - .:/app
      - /app/node_modules
    depends_on:
      - db
  
  db:
    image: postgres:latest
    ports:
    - 5432:5432
    environment:
      POSTGRES_DB: gobarber
      POSTGRES_PASSWORD: gobarber
    restart: always    
    