version: "3.7"

services:
  db:
    image: postgres:13
    container_name: database_gobarber
    environment:
      POSTGRES_PASSWORD: gobarber
      POSTGRES_USER: gobarber
      POSTGRES_DB: gobarber
    volumes:
      - ./db-data:/var/lib/postgresql/data
    restart: always
    ports:
      - "5432:5432"
  api:
    build:
      context: .
    container_name: api
    command: yarn dev:server
    environment:
      NODE_ENV: ${NODE_ENV}
    ports:
      - "3333:3333"
    volumes:
      - .:/app
    depends_on:
      - db
